-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Locations table (e.g. Jakarta, Surabaya, Bandung ...)
CREATE TABLE IF NOT EXISTS locations (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name        VARCHAR(100) NOT NULL UNIQUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Users table
CREATE TABLE IF NOT EXISTS users (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name        VARCHAR(100) NOT NULL,
    email       VARCHAR(150) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    role        VARCHAR(20)  NOT NULL DEFAULT 'user',  -- admin | user
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- User location access (many-to-many). Admin can bypass this.
CREATE TABLE IF NOT EXISTS user_locations (
    user_id      UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    location_id  UUID NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, location_id)
);

-- Devices table
CREATE TABLE IF NOT EXISTS devices (
    id           UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name         VARCHAR(150) NOT NULL,
    location_id  UUID NOT NULL REFERENCES locations(id),
    status       VARCHAR(20)  NOT NULL DEFAULT 'offline', -- online | offline
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_devices_location ON devices(location_id);

-- Seed default locations
INSERT INTO locations (id, name) VALUES
    ('11111111-1111-1111-1111-111111111111', 'Jakarta'),
    ('22222222-2222-2222-2222-222222222222', 'Surabaya'),
    ('33333333-3333-3333-3333-333333333333', 'Bandung')
ON CONFLICT (name) DO NOTHING;

-- Seed sample devices
INSERT INTO devices (name, location_id, status) VALUES
    ('Sensor A-1', '11111111-1111-1111-1111-111111111111', 'online'),
    ('Sensor A-2', '11111111-1111-1111-1111-111111111111', 'offline'),
    ('Sensor B-1', '22222222-2222-2222-2222-222222222222', 'online'),
    ('Sensor C-1', '33333333-3333-3333-3333-333333333333', 'offline')
ON CONFLICT DO NOTHING;

-- Default users are created at application startup (see database/seed.go)
-- so that the bcrypt hashes are generated by the running code.
