-- Enable UUID extension (users still use UUIDs)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Locations table (integer ids for readable URLs: /devices?location_id=1 )
CREATE TABLE IF NOT EXISTS locations (
    id          BIGSERIAL PRIMARY KEY,
    name        VARCHAR(100) NOT NULL UNIQUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- Users table
CREATE TABLE IF NOT EXISTS users (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name        VARCHAR(100) NOT NULL,
    email       VARCHAR(150) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    role        VARCHAR(20)  NOT NULL DEFAULT 'user',  -- admin | user
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- User location access (many-to-many). Admin bypasses this.
CREATE TABLE IF NOT EXISTS user_locations (
    user_id      UUID   NOT NULL REFERENCES users(id)     ON DELETE CASCADE,
    location_id  BIGINT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, location_id)
);

-- Devices table (integer ids)
CREATE TABLE IF NOT EXISTS devices (
    id           BIGSERIAL PRIMARY KEY,
    name         VARCHAR(150) NOT NULL,
    location_id  BIGINT NOT NULL REFERENCES locations(id),
    status       VARCHAR(20)  NOT NULL DEFAULT 'offline', -- online | offline
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_devices_location ON devices(location_id);

-- Seed default locations with explicit ids 1, 2, 3
INSERT INTO locations (id, name) VALUES
    (1, 'Jakarta'),
    (2, 'Surabaya'),
    (3, 'Bandung')
ON CONFLICT (name) DO NOTHING;

-- Advance the sequence past the manual inserts so the next create picks up >3
SELECT setval('locations_id_seq', GREATEST((SELECT COALESCE(MAX(id), 0) FROM locations), 1));

-- Seed sample devices (fixed integer ids so re-running does not duplicate)
INSERT INTO devices (id, name, location_id, status) VALUES
    -- Jakarta (location 1)
    (1, 'JKT Temperature Sensor 01', 1, 'online'),
    (2, 'JKT Humidity Sensor 01',    1, 'online'),
    (3, 'JKT Smart Meter 01',        1, 'offline'),
    (4, 'JKT CCTV Camera 01',        1, 'online'),
    -- Surabaya (location 2)
    (5, 'SBY Temperature Sensor 01', 2, 'online'),
    (6, 'SBY Smart Meter 01',        2, 'offline'),
    (7, 'SBY Door Lock 01',          2, 'online'),
    -- Bandung (location 3)
    (8, 'BDG Temperature Sensor 01', 3, 'offline'),
    (9, 'BDG Air Quality Sensor 01', 3, 'online')
ON CONFLICT (id) DO NOTHING;

SELECT setval('devices_id_seq', GREATEST((SELECT COALESCE(MAX(id), 0) FROM devices), 1));

-- Default users are created at application startup (see database/seed.go)
-- so that the bcrypt hashes are generated by the running code.
