// Package docs is a placeholder for the swagger documentation generated by
// `swag init`. It keeps the project compilable before swagger is generated.
// After running `swag init` this file will be regenerated automatically.
package docs
